name: Test Docker on GitHub Actions

on:
  push:
    branches: 
      - main
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"

permissions:
  contents: read
  packages: write

jobs:
  build_container:
    runs-on: [self-hosted]
    environment: staging
    env:
      PATH_DOCKERCOMPOSE: /opt/dobybot-css-stg/docker-compose.yml
      DOCKER_FILE_PATH: ./backend/Dockerfile
      DOCKER_BUILD_PATH: ./backend
      URL: "https://stg-css.doby.me/ticket-api/ht/"
    services:
      docker:
        image: docker:dind
        options: --privileged --shm-size=2g
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
    container:
      image: ubuntu:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Docker
        run: |
          apt-get update
          apt-get install -y docker.io

      - name: Test Docker
        run: |
          docker version
          docker info
      - name: Log in to Staging Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.STAGING_REGISTRY }}
          username: ${{ secrets.STAGING_REGISTRY_USERNAME }}
          password: ${{ secrets.STAGING_REGISTRY_PASSWORD }}
      - name: Build Container
        run: |
          docker build -t ${{ vars.STAGING_REGISTRY_IMAGE }}/backend/staging:${{ github.sha }} ${{ env.DOCKER_BUILD_PATH }} -f ${{ env.DOCKER_FILE_PATH }}
          docker push ${{ vars.STAGING_REGISTRY_IMAGE }}/backend/staging:${{ github.sha }}